'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// B2B Data Lookup (Any Input) — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "b2b_data_lookup",
  "inputLabel": "Company or Person Identifier",
  "params": [],
  "outputField": null
};

module.exports = {
  key: 'b2bDataLookup',
  noun: "Profile",

  display: {
    label: "B2B Data Lookup (Any Input)",
    description: "B2B Data Lookup (Any Input) using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Company or Person Identifier",
            "type": "string",
            "required": true,
            "helpText": "Use this only when you do not know the input type. A specific operation is more reliable.",
            "placeholder": "tesla.com"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "https://www.linkedin.com/company/tesla-motors",
      "name": "Tesla",
      "website": "tesla.com",
      "linkedin_url": "https://www.linkedin.com/company/tesla-motors"
},

    outputFields: [
      {
            "key": "name",
            "label": "Name"
      },
      {
            "key": "website",
            "label": "Website"
      },
      {
            "key": "linkedin_url",
            "label": "LinkedIn URL"
      }
],
  },
};
