'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Company Website — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "company_name_to_website",
  "inputLabel": "Company Name",
  "params": [],
  "outputField": "website",
  "altType": null
};

module.exports = {
  key: 'findCompanyWebsite',
  noun: "Website",

  display: {
    label: "Find Company Website",
    description: "Find Company Website using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Company Name",
            "type": "string",
            "required": true,
            "helpText": "The company's name.",
            "placeholder": "Tesla"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "tesla.com",
      "value": "tesla.com",
      "website": "tesla.com"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "website",
            "label": "Website"
      }
],
  },
};
