'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find LinkedIn URL from Name — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "lead_full_name_to_linkedin_url",
  "inputLabel": "Full Name and Company",
  "params": [],
  "outputField": "linkedin_url",
  "altType": null,
  "compositeInput": {
    "parts": [
      {
        "name": "name",
        "label": "Full Name",
        "required": true
      },
      {
        "name": "company",
        "label": "Company",
        "required": false
      },
      {
        "name": "location",
        "label": "Location",
        "required": false
      },
      {
        "name": "job_title",
        "label": "Job Title",
        "required": false
      }
    ],
    "joinWith": " "
  }
};

module.exports = {
  key: 'findLinkedinUrlFromName',
  noun: "LinkedIn URL",

  display: {
    label: "Find LinkedIn URL from Name",
    description: "Find LinkedIn URL from Name using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "name",
            "label": "Full Name",
            "type": "string",
            "required": true,
            "helpText": "The person's full name. \"Doe, John\" is flipped to \"John Doe\" automatically.",
            "placeholder": "Bill Gates"
    },
      {
            "key": "company",
            "label": "Company",
            "type": "string",
            "required": false,
            "helpText": "Where they work. Much the strongest signal after the name. Optional, and free — it costs no extra credits and narrows the match.",
            "placeholder": "Microsoft"
    },
      {
            "key": "location",
            "label": "Location",
            "type": "string",
            "required": false,
            "helpText": "City, region or country. Separates people who share a name. Optional, and free — it costs no extra credits and narrows the match.",
            "placeholder": "Seattle"
    },
      {
            "key": "job_title",
            "label": "Job Title",
            "type": "string",
            "required": false,
            "helpText": "Their role. Helps when a company has several people with the same name. Optional, and free — it costs no extra credits and narrows the match.",
            "placeholder": "Co-chair"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "https://www.linkedin.com/in/williamhgates",
      "value": "https://www.linkedin.com/in/williamhgates",
      "linkedin_url": "https://www.linkedin.com/in/williamhgates"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "linkedin_url",
            "label": "LinkedIn URL"
      }
],
  },
};
