'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Leads with AI — 1 credit.
// Always asynchronous: the API returns a job and the search polls it until it
// resolves or Zapier runs out of time waiting.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "leads_finder_ai",
  "inputLabel": "Describe the Leads You Want",
  "params": [
    "fetch_count"
  ],
  "outputField": null
};

module.exports = {
  key: 'findLeadsWithAi',
  noun: "Result",

  display: {
    label: "Find Leads with AI",
    description: "Find Leads with AI using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Describe the Leads You Want",
            "type": "string",
            "required": true,
            "helpText": "Plain English — job titles, industry, company size, location.",
            "placeholder": "VP Sales at B2B SaaS startups in the United States"
    },
      {
            "key": "fetch_count",
            "label": "Number of Leads",
            "type": "integer",
            "required": false,
            "helpText": "How many leads to return.",
            "default": "10"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "https://www.linkedin.com/in/ada-lovelace",
      "name": "Ada Lovelace",
      "headline": "VP Sales at Northwind",
      "email": "ada@northwind.com",
      "linkedinUrl": "https://www.linkedin.com/in/ada-lovelace",
      "company": "Northwind",
      "companyWebsite": "northwind.com"
},

    outputFields: [
      {
            "key": "name",
            "label": "Name"
      },
      {
            "key": "headline",
            "label": "Headline"
      },
      {
            "key": "email",
            "label": "Email"
      },
      {
            "key": "linkedinUrl",
            "label": "LinkedIn URL"
      },
      {
            "key": "company",
            "label": "Company"
      },
      {
            "key": "companyWebsite",
            "label": "Company Website"
      }
],
  },
};
