'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Company Employee Count — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "company_name_to_employee_count",
  "inputLabel": "Company Name",
  "params": [],
  "outputField": "employee_count",
  "altType": null,
  "compositeInput": null
};

module.exports = {
  key: 'findCompanyEmployeeCount',
  noun: "Employee Count",

  display: {
    label: "Find Company Employee Count",
    description: "Find Company Employee Count using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Company Name",
            "type": "string",
            "required": true,
            "helpText": "The company's name.",
            "placeholder": "Tesla"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "140473",
      "value": 140473,
      "employee_count": 140473
},

    outputFields: [
      {
            "key": "value",
            "label": "Value",
            "type": "integer"
      },
      {
            "key": "employee_count",
            "label": "Employee Count",
            "type": "integer"
      }
],
  },
};
