'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Company Email by Domain — 5 credits.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "company_domain_to_email",
  "inputLabel": "Company Domain",
  "params": [],
  "outputField": "email",
  "altType": null,
  "compositeInput": null
};

module.exports = {
  key: 'findCompanyEmailByDomain',
  noun: "Email",

  display: {
    label: "Find Company Email by Domain",
    description: "Find Company Email by Domain using LinkFinder AI. Costs 5 credits per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Company Domain",
            "type": "string",
            "required": true,
            "helpText": "The company's domain, not its name — tesla.com, not Tesla.",
            "placeholder": "tesla.com"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "press@tesla.com",
      "value": "press@tesla.com",
      "email": "press@tesla.com"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "email",
            "label": "Email"
      }
],
  },
};
