'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Email from LinkedIn Profile — 10 credits.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "linkedin_profile_to_email",
  "inputLabel": "LinkedIn Profile URL",
  "params": [],
  "outputField": "email"
};

module.exports = {
  key: 'findEmailFromLinkedinProfile',
  noun: "Email",

  display: {
    label: "Find Email from LinkedIn Profile",
    description: "Find Email from LinkedIn Profile using LinkFinder AI. Costs 10 credits per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "LinkedIn Profile URL",
            "type": "string",
            "required": true,
            "helpText": "A LinkedIn person profile URL.",
            "placeholder": "https://www.linkedin.com/in/someone"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "bill.gates@microsoft.com",
      "value": "bill.gates@microsoft.com",
      "email": "bill.gates@microsoft.com"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "email",
            "label": "Email"
      }
],
  },
};
