'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Email from Name — 7 credits.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "lead_full_name_to_email",
  "inputLabel": "Full Name and Company",
  "params": [],
  "outputField": "email"
};

module.exports = {
  key: 'findEmailFromName',
  noun: "Email",

  display: {
    label: "Find Email from Name",
    description: "Find Email from Name using LinkFinder AI. Costs 7 credits per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Full Name and Company",
            "type": "string",
            "required": true,
            "helpText": "The person's full name and their company, in one string.",
            "placeholder": "Bill Gates Microsoft"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "bill.gates@microsoft.com",
      "value": "bill.gates@microsoft.com",
      "email": "bill.gates@microsoft.com"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "email",
            "label": "Email"
      }
],
  },
};
