'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find LinkedIn URL from Email — 5 credits.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "email_to_linkedin_url",
  "inputLabel": "Email Address",
  "params": [],
  "outputField": "linkedin_url"
};

module.exports = {
  key: 'findLinkedinUrlFromEmail',
  noun: "LinkedIn URL",

  display: {
    label: "Find LinkedIn URL from Email",
    description: "Find LinkedIn URL from Email using LinkFinder AI. Costs 5 credits per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Email Address",
            "type": "string",
            "required": true,
            "helpText": "A professional email address.",
            "placeholder": "john.doe@company.com"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "https://www.linkedin.com/in/williamhgates",
      "value": "https://www.linkedin.com/in/williamhgates",
      "linkedin_url": "https://www.linkedin.com/in/williamhgates"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "linkedin_url",
            "label": "LinkedIn URL"
      }
],
  },
};
