'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Company LinkedIn URL — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "company_name_to_linkedin_url",
  "inputLabel": "Company Name",
  "params": [],
  "outputField": "linkedin_url",
  "altType": null,
  "compositeInput": null
};

module.exports = {
  key: 'findCompanyLinkedinUrl',
  noun: "LinkedIn URL",

  display: {
    label: "Find Company LinkedIn URL",
    description: "Find Company LinkedIn URL using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Company Name",
            "type": "string",
            "required": true,
            "helpText": "The company's name.",
            "placeholder": "Tesla"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "https://www.linkedin.com/company/tesla-motors",
      "value": "https://www.linkedin.com/company/tesla-motors",
      "linkedin_url": "https://www.linkedin.com/company/tesla-motors"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "linkedin_url",
            "label": "LinkedIn URL"
      }
],
  },
};
