'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find LinkedIn URL from Name — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "lead_full_name_to_linkedin_url",
  "inputLabel": "Full Name and Company",
  "params": [],
  "outputField": "linkedin_url"
};

module.exports = {
  key: 'findLinkedinUrlFromName',
  noun: "LinkedIn URL",

  display: {
    label: "Find LinkedIn URL from Name",
    description: "Find LinkedIn URL from Name using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Full Name and Company",
            "type": "string",
            "required": true,
            "helpText": "The person's full name and their company, in one string.",
            "placeholder": "Bill Gates Microsoft"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "https://www.linkedin.com/in/williamhgates",
      "value": "https://www.linkedin.com/in/williamhgates",
      "linkedin_url": "https://www.linkedin.com/in/williamhgates"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "linkedin_url",
            "label": "LinkedIn URL"
      }
],
  },
};
