'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Company Phone — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "company_name_to_phone",
  "inputLabel": "Company Name",
  "params": [],
  "outputField": "phone",
  "altType": null,
  "compositeInput": null
};

module.exports = {
  key: 'findCompanyPhone',
  noun: "Phone",

  display: {
    label: "Find Company Phone",
    description: "Find Company Phone using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Company Name",
            "type": "string",
            "required": true,
            "helpText": "The company's name.",
            "placeholder": "Tesla"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "+1 512 516 8177",
      "value": "+1 512 516 8177",
      "phone": "+1 512 516 8177"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "phone",
            "label": "Phone"
      }
],
  },
};
