'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Phone from LinkedIn Profile — 50 credits.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "linkedin_profile_to_phone",
  "inputLabel": "LinkedIn Profile URL",
  "params": [],
  "outputField": "phone",
  "altType": null,
  "compositeInput": null
};

module.exports = {
  key: 'findPhoneFromLinkedinProfile',
  noun: "Phone",

  display: {
    label: "Find Phone from LinkedIn Profile",
    description: "Find Phone from LinkedIn Profile using LinkFinder AI. Costs 50 credits per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "LinkedIn Profile URL",
            "type": "string",
            "required": true,
            "helpText": "A LinkedIn person profile URL.",
            "placeholder": "https://www.linkedin.com/in/someone"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "+1 425 882 8080",
      "value": "+1 425 882 8080",
      "phone": "+1 425 882 8080"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "phone",
            "label": "Phone"
      }
],
  },
};
