'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Find Company Email — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "company_name_to_email",
  "inputLabel": "Company Name",
  "params": [],
  "outputField": "email"
};

module.exports = {
  key: 'findCompanyEmail',
  noun: "Email",

  display: {
    label: "Find Company Email",
    description: "Find Company Email using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Company Name",
            "type": "string",
            "required": true,
            "helpText": "The company's name.",
            "placeholder": "Tesla"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "press@tesla.com",
      "value": "press@tesla.com",
      "email": "press@tesla.com"
},

    outputFields: [
      {
            "key": "value",
            "label": "Value"
      },
      {
            "key": "email",
            "label": "Email"
      }
],
  },
};
