'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Get LinkedIn Profile Details — 10 credits.
// Always asynchronous: the API returns a job and the search polls it until it
// resolves or Zapier runs out of time waiting.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "linkedin_profile_to_linkedin_info",
  "inputLabel": "LinkedIn Profile URL",
  "params": [],
  "outputField": null,
  "altType": null,
  "compositeInput": null
};

module.exports = {
  key: 'getLinkedinProfileDetails',
  noun: "Profile",

  display: {
    label: "Get LinkedIn Profile Details",
    description: "Get LinkedIn Profile Details using LinkFinder AI. Costs 10 credits per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "LinkedIn Profile URL",
            "type": "string",
            "required": true,
            "helpText": "A LinkedIn person profile URL.",
            "placeholder": "https://www.linkedin.com/in/someone"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "https://www.linkedin.com/in/williamhgates",
      "name": "Bill Gates",
      "jobTitle": "Co-chair",
      "company": "Gates Foundation",
      "location": "Seattle United States of America",
      "country": "United States of America",
      "industry": "",
      "about": "Chair of the Gates Foundation. Founder of Breakthrough Energy.",
      "headline": "Chair, Gates Foundation and Founder, Breakthrough Energy",
      "connections": "",
      "followers": "",
      "mobileNumber": "",
      "email": "",
      "website": "",
      "linkedinUrl": "https://www.linkedin.com/in/williamhgates",
      "company_linkedin_url": "https://www.linkedin.com/company/8736",
      "profilePic": "https://storage.googleapis.com/linkedin_profile_picture/williamhgates.jpeg",
      "backgroundPic": "",
      "isJobSeeker": "false",
      "isCurrentlyEmployed": "true",
      "firstRoleYear": "1975",
      "experiences": [
            {
                  "companyName": "Microsoft",
                  "companyLink": "https://www.linkedin.com/company/microsoft",
                  "title": "Co-founder",
                  "jobStartedOn": "1975",
                  "jobEndedOn": "",
                  "jobStillWorking": true
            }
      ],
      "education": [
            {
                  "school": "Harvard University",
                  "schoolLink": "https://www.linkedin.com/school/harvard-university",
                  "degree": "",
                  "fieldOfStudy": "",
                  "startDate": "1973",
                  "endDate": "1975"
            }
      ],
      "skills": [],
      "languages": [],
      "certifications": [],
      "verified": "true"
},

    outputFields: [
      {
            "key": "name",
            "label": "Name"
      },
      {
            "key": "jobTitle",
            "label": "Job Title"
      },
      {
            "key": "company",
            "label": "Company"
      },
      {
            "key": "location",
            "label": "Location"
      },
      {
            "key": "country",
            "label": "Country"
      },
      {
            "key": "industry",
            "label": "Industry"
      },
      {
            "key": "about",
            "label": "About"
      },
      {
            "key": "headline",
            "label": "Headline"
      },
      {
            "key": "connections",
            "label": "Connections"
      },
      {
            "key": "followers",
            "label": "Followers"
      },
      {
            "key": "mobileNumber",
            "label": "Mobile Number"
      },
      {
            "key": "email",
            "label": "Email"
      },
      {
            "key": "website",
            "label": "Website"
      },
      {
            "key": "linkedinUrl",
            "label": "LinkedIn URL"
      },
      {
            "key": "company_linkedin_url",
            "label": "Company LinkedIn URL"
      },
      {
            "key": "profilePic",
            "label": "Profile Pic"
      },
      {
            "key": "backgroundPic",
            "label": "Background Pic"
      },
      {
            "key": "isJobSeeker",
            "label": "Is Job Seeker"
      },
      {
            "key": "isCurrentlyEmployed",
            "label": "Is Currently Employed"
      },
      {
            "key": "firstRoleYear",
            "label": "First Role Year"
      },
      {
            "key": "experiences",
            "label": "Experiences"
      },
      {
            "key": "education",
            "label": "Education"
      },
      {
            "key": "skills",
            "label": "Skills"
      },
      {
            "key": "languages",
            "label": "Languages"
      },
      {
            "key": "certifications",
            "label": "Certifications"
      },
      {
            "key": "verified",
            "label": "Verified"
      }
],
  },
};
