'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Get LinkedIn Post Reactions — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "linkedin_post_to_reactions",
  "inputLabel": "LinkedIn Post URL",
  "params": [],
  "outputField": null
};

module.exports = {
  key: 'getLinkedinPostReactions',
  noun: "Result",

  display: {
    label: "Get LinkedIn Post Reactions",
    description: "Get LinkedIn Post Reactions using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "LinkedIn Post URL",
            "type": "string",
            "required": true,
            "helpText": "A LinkedIn post URL.",
            "placeholder": "https://www.linkedin.com/posts/someone_activity-123"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "https://www.linkedin.com/in/ada-lovelace",
      "name": "Ada Lovelace",
      "headline": "VP Engineering at Tesla",
      "linkedinUrl": "https://www.linkedin.com/in/ada-lovelace",
      "reactionType": "LIKE"
},

    outputFields: [
      {
            "key": "name",
            "label": "Name"
      },
      {
            "key": "headline",
            "label": "Headline"
      },
      {
            "key": "linkedinUrl",
            "label": "LinkedIn URL"
      },
      {
            "key": "reactionType",
            "label": "Reaction Type"
      }
],
  },
};
