'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Get Employee Count from LinkedIn Company — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "linkedin_company_to_employee_count",
  "inputLabel": "LinkedIn Company Page URL",
  "params": [],
  "outputField": "employee_count",
  "altType": null,
  "compositeInput": null
};

module.exports = {
  key: 'getLinkedinCompanyEmployeeCount',
  noun: "Employee Count",

  display: {
    label: "Get Employee Count from LinkedIn Company",
    description: "Get Employee Count from LinkedIn Company using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "LinkedIn Company Page URL",
            "type": "string",
            "required": true,
            "helpText": "A LinkedIn company page URL.",
            "placeholder": "https://www.linkedin.com/company/tesla-motors"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "140473",
      "value": 140473,
      "employee_count": 140473
},

    outputFields: [
      {
            "key": "value",
            "label": "Value",
            "type": "integer"
      },
      {
            "key": "employee_count",
            "label": "Employee Count",
            "type": "integer"
      }
],
  },
};
