'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Get LinkedIn Profile Details — 10 credits.
// Always asynchronous: the API returns a job and the search polls it until it
// resolves or Zapier runs out of time waiting.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "linkedin_profile_to_linkedin_info",
  "inputLabel": "LinkedIn Profile URL",
  "params": [],
  "outputField": null
};

module.exports = {
  key: 'getLinkedinProfileDetails',
  noun: "Profile",

  display: {
    label: "Get LinkedIn Profile Details",
    description: "Get LinkedIn Profile Details using LinkFinder AI. Costs 10 credits per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "LinkedIn Profile URL",
            "type": "string",
            "required": true,
            "helpText": "A LinkedIn person profile URL.",
            "placeholder": "https://www.linkedin.com/in/someone"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "gatesnotes.com",
      "headline": "Co-chair, Bill & Melinda Gates Foundation",
      "job_title": "Co-chair",
      "company": "Bill & Melinda Gates Foundation",
      "location": "Seattle, Washington, United States",
      "follower_count": 35000000,
      "email": "bill.gates@microsoft.com",
      "mobile_number": "+1 425 882 8080",
      "website": "gatesnotes.com",
      "experience": [],
      "education": []
},

    outputFields: [
      {
            "key": "headline",
            "label": "Headline"
      },
      {
            "key": "job_title",
            "label": "Job Title"
      },
      {
            "key": "company",
            "label": "Company"
      },
      {
            "key": "location",
            "label": "Location"
      },
      {
            "key": "follower_count",
            "label": "Follower Count",
            "type": "integer"
      },
      {
            "key": "email",
            "label": "Email"
      },
      {
            "key": "mobile_number",
            "label": "Mobile Number"
      },
      {
            "key": "website",
            "label": "Website"
      },
      {
            "key": "experience",
            "label": "Experience"
      },
      {
            "key": "education",
            "label": "Education"
      }
],
  },
};
