'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Get LinkedIn Company Details — 6 credits.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "linkedin_company_to_linkedin_info",
  "inputLabel": "LinkedIn Company Page URL",
  "params": [],
  "outputField": null
};

module.exports = {
  key: 'getLinkedinCompanyDetails',
  noun: "Company",

  display: {
    label: "Get LinkedIn Company Details",
    description: "Get LinkedIn Company Details using LinkFinder AI. Costs 6 credits per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "LinkedIn Company Page URL",
            "type": "string",
            "required": true,
            "helpText": "A LinkedIn company page URL.",
            "placeholder": "https://www.linkedin.com/company/tesla-motors"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "tesla.com",
      "name": "Tesla",
      "website": "tesla.com",
      "industry": "Motor Vehicle Manufacturing",
      "employee_count": 140473,
      "location": "Austin, Texas",
      "founded": 2003,
      "description": "Tesla accelerates the world to sustainable energy."
},

    outputFields: [
      {
            "key": "name",
            "label": "Name"
      },
      {
            "key": "website",
            "label": "Website"
      },
      {
            "key": "industry",
            "label": "Industry"
      },
      {
            "key": "employee_count",
            "label": "Employee Count",
            "type": "integer"
      },
      {
            "key": "location",
            "label": "Location"
      },
      {
            "key": "founded",
            "label": "Founded",
            "type": "integer"
      },
      {
            "key": "description",
            "label": "Description"
      }
],
  },
};
