'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.

const findLinkedinUrlFromName = require('./findLinkedinUrlFromName');
const findLinkedinUrlFromEmail = require('./findLinkedinUrlFromEmail');
const findEmailFromName = require('./findEmailFromName');
const findEmailFromLinkedinProfile = require('./findEmailFromLinkedinProfile');
const getLinkedinProfileDetails = require('./getLinkedinProfileDetails');
const findPhoneFromLinkedinProfile = require('./findPhoneFromLinkedinProfile');
const findCompanyEmail = require('./findCompanyEmail');
const findCompanyEmployeeCount = require('./findCompanyEmployeeCount');
const findCompanyLinkedinUrl = require('./findCompanyLinkedinUrl');
const findCompanyPhone = require('./findCompanyPhone');
const findCompanyWebsite = require('./findCompanyWebsite');
const getLinkedinCompanyEmployeeCount = require('./getLinkedinCompanyEmployeeCount');
const listEmployeesByCompanyDomain = require('./listEmployeesByCompanyDomain');
const listEmployeesByCompanyName = require('./listEmployeesByCompanyName');
const listEmployeesFromLinkedinCompany = require('./listEmployeesFromLinkedinCompany');
const getLinkedinCompanyDetails = require('./getLinkedinCompanyDetails');
const getLinkedinPostReactions = require('./getLinkedinPostReactions');
const lookUpInstagramProfile = require('./lookUpInstagramProfile');
const b2bDataLookup = require('./b2bDataLookup');
const findLeadsWithAi = require('./findLeadsWithAi');

module.exports = {
  [findLinkedinUrlFromName.key]: findLinkedinUrlFromName,
  [findLinkedinUrlFromEmail.key]: findLinkedinUrlFromEmail,
  [findEmailFromName.key]: findEmailFromName,
  [findEmailFromLinkedinProfile.key]: findEmailFromLinkedinProfile,
  [getLinkedinProfileDetails.key]: getLinkedinProfileDetails,
  [findPhoneFromLinkedinProfile.key]: findPhoneFromLinkedinProfile,
  [findCompanyEmail.key]: findCompanyEmail,
  [findCompanyEmployeeCount.key]: findCompanyEmployeeCount,
  [findCompanyLinkedinUrl.key]: findCompanyLinkedinUrl,
  [findCompanyPhone.key]: findCompanyPhone,
  [findCompanyWebsite.key]: findCompanyWebsite,
  [getLinkedinCompanyEmployeeCount.key]: getLinkedinCompanyEmployeeCount,
  [listEmployeesByCompanyDomain.key]: listEmployeesByCompanyDomain,
  [listEmployeesByCompanyName.key]: listEmployeesByCompanyName,
  [listEmployeesFromLinkedinCompany.key]: listEmployeesFromLinkedinCompany,
  [getLinkedinCompanyDetails.key]: getLinkedinCompanyDetails,
  [getLinkedinPostReactions.key]: getLinkedinPostReactions,
  [lookUpInstagramProfile.key]: lookUpInstagramProfile,
  [b2bDataLookup.key]: b2bDataLookup,
  [findLeadsWithAi.key]: findLeadsWithAi,
};
