'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// List Employees from LinkedIn Company — 0.5 credits per employee returned.
// Always asynchronous: the API returns a job and the search polls it until it
// resolves or Zapier runs out of time waiting.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "linkedin_company_to_employees",
  "inputLabel": "LinkedIn Company Page URL",
  "params": [
    "department",
    "seniority",
    "employee_count"
  ],
  "outputField": null,
  "altType": null,
  "compositeInput": null
};

module.exports = {
  key: 'listEmployeesFromLinkedinCompany',
  noun: "Result",

  display: {
    label: "List Employees from LinkedIn Company",
    description: "List Employees from LinkedIn Company using LinkFinder AI. Billed 0.5 credits per employee returned.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "LinkedIn Company Page URL",
            "type": "string",
            "required": true,
            "helpText": "A LinkedIn company page URL.",
            "placeholder": "https://www.linkedin.com/company/tesla-motors"
    },
      {
            "key": "department",
            "label": "Department",
            "type": "string",
            "required": false,
            "helpText": "Only return employees in this department, e.g. Engineering."
    },
      {
            "key": "seniority",
            "label": "Seniority",
            "type": "string",
            "required": false,
            "helpText": "Only return employees at this seniority, e.g. Director."
    },
      {
            "key": "employee_count",
            "label": "Max Employees",
            "type": "integer",
            "required": false,
            "helpText": "Cap how many employees come back. Billed 0.5 credits each."
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "http://www.linkedin.com/in/sebastian-robles-00277a305",
      "personId": "664cc61ecb4c2f0001ddb8b9",
      "name": "Sebastian Robles",
      "firstName": "Sebastian",
      "lastName": "Robles",
      "jobTitle": "Talent Acquisition Manager",
      "headline": "Talent Acquisition Manager en Tesla",
      "seniority": "manager",
      "department": [
            "Human Resources"
      ],
      "industry": "Automotive",
      "photoUrl": null,
      "email": "srobles@tesla.com",
      "mobileNumber": null,
      "twitter": null,
      "linkedinUrl": "http://www.linkedin.com/in/sebastian-robles-00277a305",
      "city": "Mexico City",
      "state": "Mexico City",
      "country": "Mexico",
      "companyId": "57c4d9dea6da9869f38f20af",
      "company": "Tesla",
      "companyWebsite": "tesla.com",
      "companySize": null,
      "companyLinkedinUrl": "http://www.linkedin.com/company/tesla-motors",
      "companyPhone": "+16506815000",
      "companyCity": "Austin",
      "companyState": "Texas",
      "companyCountry": "United States"
},

    outputFields: [
      {
            "key": "personId",
            "label": "Person Id"
      },
      {
            "key": "name",
            "label": "Name"
      },
      {
            "key": "firstName",
            "label": "First Name"
      },
      {
            "key": "lastName",
            "label": "Last Name"
      },
      {
            "key": "jobTitle",
            "label": "Job Title"
      },
      {
            "key": "headline",
            "label": "Headline"
      },
      {
            "key": "seniority",
            "label": "Seniority"
      },
      {
            "key": "department",
            "label": "Department"
      },
      {
            "key": "industry",
            "label": "Industry"
      },
      {
            "key": "photoUrl",
            "label": "Photo URL"
      },
      {
            "key": "email",
            "label": "Email"
      },
      {
            "key": "mobileNumber",
            "label": "Mobile Number"
      },
      {
            "key": "twitter",
            "label": "Twitter"
      },
      {
            "key": "linkedinUrl",
            "label": "LinkedIn URL"
      },
      {
            "key": "city",
            "label": "City"
      },
      {
            "key": "state",
            "label": "State"
      },
      {
            "key": "country",
            "label": "Country"
      },
      {
            "key": "companyId",
            "label": "Company Id"
      },
      {
            "key": "company",
            "label": "Company"
      },
      {
            "key": "companyWebsite",
            "label": "Company Website"
      },
      {
            "key": "companySize",
            "label": "Company Size"
      },
      {
            "key": "companyLinkedinUrl",
            "label": "Company LinkedIn URL"
      },
      {
            "key": "companyPhone",
            "label": "Company Phone"
      },
      {
            "key": "companyCity",
            "label": "Company City"
      },
      {
            "key": "companyState",
            "label": "Company State"
      },
      {
            "key": "companyCountry",
            "label": "Company Country"
      }
],
  },
};
