'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// List Employees by Company Name — 0.5 credits per employee returned.
// Always asynchronous: the API returns a job and the search polls it until it
// resolves or Zapier runs out of time waiting.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "company_name_to_employees",
  "inputLabel": "Company Name",
  "params": [
    "department",
    "seniority",
    "employee_count"
  ],
  "outputField": null
};

module.exports = {
  key: 'listEmployeesByCompanyName',
  noun: "Result",

  display: {
    label: "List Employees by Company Name",
    description: "List Employees by Company Name using LinkFinder AI. Billed 0.5 credits per employee returned.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Company Name",
            "type": "string",
            "required": true,
            "helpText": "The company's name.",
            "placeholder": "Tesla"
    },
      {
            "key": "department",
            "label": "Department",
            "type": "string",
            "required": false,
            "helpText": "Only return employees in this department, e.g. Engineering."
    },
      {
            "key": "seniority",
            "label": "Seniority",
            "type": "string",
            "required": false,
            "helpText": "Only return employees at this seniority, e.g. Director."
    },
      {
            "key": "employee_count",
            "label": "Max Employees",
            "type": "integer",
            "required": false,
            "helpText": "Cap how many employees come back. Billed 0.5 credits each."
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "https://www.linkedin.com/in/ada-lovelace",
      "name": "Ada Lovelace",
      "headline": "VP Engineering at Tesla",
      "email": "ada.lovelace@tesla.com",
      "linkedinUrl": "https://www.linkedin.com/in/ada-lovelace",
      "photoUrl": "https://media.licdn.com/dms/image/example.jpg",
      "company": "Tesla",
      "companyWebsite": "tesla.com",
      "companyPhone": "+1 512 516 8177",
      "companySize": "10001+",
      "companyCity": "Austin",
      "companyState": "Texas",
      "companyCountry": "United States",
      "companyLinkedinUrl": "https://www.linkedin.com/company/tesla-motors"
},

    outputFields: [
      {
            "key": "name",
            "label": "Name"
      },
      {
            "key": "headline",
            "label": "Headline"
      },
      {
            "key": "email",
            "label": "Email"
      },
      {
            "key": "linkedinUrl",
            "label": "LinkedIn URL"
      },
      {
            "key": "photoUrl",
            "label": "Photo URL"
      },
      {
            "key": "company",
            "label": "Company"
      },
      {
            "key": "companyWebsite",
            "label": "Company Website"
      },
      {
            "key": "companyPhone",
            "label": "Company Phone"
      },
      {
            "key": "companySize",
            "label": "Company Size"
      },
      {
            "key": "companyCity",
            "label": "Company City"
      },
      {
            "key": "companyState",
            "label": "Company State"
      },
      {
            "key": "companyCountry",
            "label": "Company Country"
      },
      {
            "key": "companyLinkedinUrl",
            "label": "Company LinkedIn URL"
      }
],
  },
};
