'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Look Up an Instagram Profile — 1 credit.

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = {
  "type": "instagram_lookup",
  "inputLabel": "Instagram Handle or URL",
  "params": [],
  "outputField": null,
  "altType": "instagram_profile_to_instagram_info",
  "compositeInput": null
};

module.exports = {
  key: 'lookUpInstagramProfile',
  noun: "Profile",

  display: {
    label: "Look Up an Instagram Profile",
    description: "Look Up an Instagram Profile using LinkFinder AI. Costs 1 credit per lookup, including lookups that find nothing.",
  },

  operation: {
    inputFields: [
      {
            "key": "input_data",
            "label": "Instagram Handle or URL",
            "type": "string",
            "required": true,
            "helpText": "An Instagram handle or profile URL.",
            "placeholder": "@nasa"
    }
],

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: {
      "id": "nasa.gov",
      "username": "nasa",
      "full_name": "NASA",
      "follower_count": 97000000,
      "biography": "Explore the universe and discover our home planet.",
      "website": "nasa.gov",
      "is_verified": true
},

    outputFields: [
      {
            "key": "username",
            "label": "Username"
      },
      {
            "key": "full_name",
            "label": "Full Name"
      },
      {
            "key": "follower_count",
            "label": "Follower Count",
            "type": "integer"
      },
      {
            "key": "biography",
            "label": "Biography"
      },
      {
            "key": "website",
            "label": "Website"
      },
      {
            "key": "is_verified",
            "label": "Is Verified",
            "type": "boolean"
      }
],
  },
};
