/**
 * Generates src/generated/operations.js from integrations/catalog/operations.json.
 *
 * The extension only ever runs on a LinkedIn page, so it offers exactly those
 * catalog operations whose *input is a LinkedIn URL* — the URL is already in the
 * address bar, which is the entire reason an extension beats the web app here.
 *
 * That set is DERIVED, not listed: an operation qualifies by its input label, so
 * a new LinkedIn operation added to the catalog appears in the extension on the
 * next build without anyone remembering to come here. Operations needing input
 * the page cannot supply (a name, an email, a company domain) are excluded by
 * the same rule, which is why there is no deny-list either.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(readFileSync(join(HERE, '..', 'catalog', 'operations.json'), 'utf8'));

// Input label -> which LinkedIn page supplies that URL. The path fragment is what
// the content script matches on; order matters only in that each is distinct.
const PAGES = {
    'LinkedIn Profile URL': { page: 'profile', match: '/in/', pageLabel: 'this profile' },
    'LinkedIn Company Page URL': { page: 'company', match: '/company/', pageLabel: 'this company' },
    'LinkedIn Post URL': { page: 'post', match: '/posts/', pageLabel: 'this post' },
};

const operations = catalog.operations
    .filter((op) => PAGES[op.input.label])
    .map((op) => ({
        type: op.type,
        label: op.label,
        // The in-page button has room for a verb, not a sentence.
        short: op.label.replace(/^(Find|Get|List)\s+/, '').replace(/\s+from LinkedIn.*$/, ''),
        credits: op.credits,
        perEmployeeBilling: op.perEmployeeBilling,
        alwaysAsync: op.alwaysAsync,
        page: PAGES[op.input.label].page,
        pageMatch: PAGES[op.input.label].match,
        outputKind: op.output.kind,
        outputField: op.output.field,
        // The catalog already decides which fields belong in an export and which
        // are internal ids, so the CSV columns come from there rather than being
        // decided again here and drifting from the Sheets add-on's export.
        columns: op.output.columns || null,
        params: op.params.map((p) => ({ name: p.name, label: p.label, type: p.type, help: p.help })),
    }));

if (!operations.length) throw new Error('no LinkedIn-input operations found — did the catalog input labels change?');

const pages = [...new Set(operations.map((o) => o.page))];
for (const page of pages) {
    if (!operations.some((o) => o.page === page)) throw new Error(`page ${page} has no operations`);
}

mkdirSync(join(HERE, 'src', 'generated'), { recursive: true });
writeFileSync(
    join(HERE, 'src', 'generated', 'operations.js'),
    `// GENERATED by integrations/chrome-extension/build.mjs from
// integrations/catalog/operations.json. Do not edit.
//
// Spec version ${catalog.specVersion} — ${operations.length} of ${catalog.operations.length}
// operations, being those whose input is a LinkedIn URL.

export const API_BASE = ${JSON.stringify(catalog.apiBase)};

export const SPEC_VERSION = ${JSON.stringify(catalog.specVersion)};

export const OPERATIONS = ${JSON.stringify(operations, null, 4)};

/** Which LinkedIn page a URL is, or null if it is not one we act on. */
export function pageTypeOf(url) {
    for (const op of OPERATIONS) {
        if (url.includes(op.pageMatch)) return op.page;
    }
    return null;
}

/** The operations offered on a given page type, cheapest first. */
export function operationsFor(page) {
    return OPERATIONS.filter((op) => op.page === page).sort((a, b) => a.credits - b.credits);
}

/**
 * What an operation will actually cost, given the requested row cap.
 *
 * Per-employee billing is the only place the headline credit number lies: the
 * catalog says 1 credit for an employee export, but 200 employees is 101. A user
 * who learns that from their balance has been mugged, so the panel quotes this
 * before the button is pressed, not after.
 */
export function estimateCredits(operation, rows) {
    if (!operation.perEmployeeBilling) return operation.credits;
    const n = Number(rows);
    if (!Number.isFinite(n) || n <= 0) return null;
    return operation.credits + 0.5 * n;
}

/** Operations that return many rows, i.e. the ones worth a CSV. */
export function isExport(operation) {
    return operation.outputKind === 'list';
}

export function operationByType(type) {
    return OPERATIONS.find((op) => op.type === type) || null;
}
`
);

console.log(`chrome-extension: ${operations.length} operations across ${pages.length} page types (${pages.join(', ')})`);
