/**
 * Generates Operations.gs from integrations/catalog/operations.json.
 *
 * Apps Script has no module system worth the name, so the operation list is emitted as
 * a plain global — but it comes from the same catalog as every other integration, so
 * the sheet add-on cannot offer an operation the API does not have, or price one wrong.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(readFileSync(join(HERE, '..', 'catalog', 'operations.json'), 'utf8'));

const operations = catalog.operations.map((op) => ({
  type: op.type,
  label: op.label,
  category: op.categoryLabel,
  credits: op.credits,
  perEmployeeBilling: op.perEmployeeBilling,
  alwaysAsync: op.alwaysAsync,
  altType: op.altType,
  inputLabel: op.input.label,
  inputHelp: op.input.help,
  example: String(op.input.example),
  outputField: op.output.field,
  outputKind: op.output.kind,
  params: op.params.map((p) => ({ name: p.name, label: p.label, type: p.type })),
}));

writeFileSync(
  join(HERE, 'Operations.gs'),
  `// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Spec version ${catalog.specVersion} — ${operations.length} operations.

var LINKFINDER_API_BASE = ${JSON.stringify(catalog.apiBase)};

var LINKFINDER_OPERATIONS = ${JSON.stringify(operations, null, 2)};

/** Looks an operation up by its API type. */
function lfOperation(type) {
  for (var i = 0; i < LINKFINDER_OPERATIONS.length; i++) {
    if (LINKFINDER_OPERATIONS[i].type === type) return LINKFINDER_OPERATIONS[i];
  }
  return null;
}
`,
);

console.log(`google-sheets: generated ${operations.length} operations from spec v${catalog.specVersion}`);
