// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// Spec version 1.1.0 — 20 operations.

var LINKFINDER_API_BASE = "https://api.linkfinderai.com";

var LINKFINDER_OPERATIONS = [
  {
    "type": "lead_full_name_to_linkedin_url",
    "label": "Find LinkedIn URL from Name",
    "category": "People",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "Full Name and Company",
    "inputHelp": "The person's full name and their company, in one string.",
    "example": "Bill Gates Microsoft",
    "outputField": "linkedin_url",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "email_to_linkedin_url",
    "label": "Find LinkedIn URL from Email",
    "category": "People",
    "credits": 5,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "Email Address",
    "inputHelp": "A professional email address.",
    "example": "john.doe@company.com",
    "outputField": "linkedin_url",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "lead_full_name_to_email",
    "label": "Find Email from Name",
    "category": "People",
    "credits": 7,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "Full Name and Company",
    "inputHelp": "The person's full name and their company, in one string.",
    "example": "Bill Gates Microsoft",
    "outputField": "email",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "linkedin_profile_to_email",
    "label": "Find Email from LinkedIn Profile",
    "category": "People",
    "credits": 10,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "LinkedIn Profile URL",
    "inputHelp": "A LinkedIn person profile URL.",
    "example": "https://www.linkedin.com/in/someone",
    "outputField": "email",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "linkedin_profile_to_linkedin_info",
    "label": "Get LinkedIn Profile Details",
    "category": "People",
    "credits": 10,
    "perEmployeeBilling": false,
    "alwaysAsync": true,
    "altType": null,
    "inputLabel": "LinkedIn Profile URL",
    "inputHelp": "A LinkedIn person profile URL.",
    "example": "https://www.linkedin.com/in/someone",
    "outputField": null,
    "outputKind": "object",
    "params": []
  },
  {
    "type": "linkedin_profile_to_phone",
    "label": "Find Phone from LinkedIn Profile",
    "category": "People",
    "credits": 50,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "LinkedIn Profile URL",
    "inputHelp": "A LinkedIn person profile URL.",
    "example": "https://www.linkedin.com/in/someone",
    "outputField": "phone",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "company_name_to_email",
    "label": "Find Company Email",
    "category": "Companies",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "Company Name",
    "inputHelp": "The company's name.",
    "example": "Tesla",
    "outputField": "email",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "company_name_to_employee_count",
    "label": "Find Company Employee Count",
    "category": "Companies",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "Company Name",
    "inputHelp": "The company's name.",
    "example": "Tesla",
    "outputField": "employee_count",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "company_name_to_linkedin_url",
    "label": "Find Company LinkedIn URL",
    "category": "Companies",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "Company Name",
    "inputHelp": "The company's name.",
    "example": "Tesla",
    "outputField": "linkedin_url",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "company_name_to_phone",
    "label": "Find Company Phone",
    "category": "Companies",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "Company Name",
    "inputHelp": "The company's name.",
    "example": "Tesla",
    "outputField": "phone",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "company_name_to_website",
    "label": "Find Company Website",
    "category": "Companies",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "Company Name",
    "inputHelp": "The company's name.",
    "example": "Tesla",
    "outputField": "website",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "linkedin_company_to_employee_count",
    "label": "Get Employee Count from LinkedIn Company",
    "category": "Companies",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "LinkedIn Company Page URL",
    "inputHelp": "A LinkedIn company page URL.",
    "example": "https://www.linkedin.com/company/tesla-motors",
    "outputField": "employee_count",
    "outputKind": "scalar",
    "params": []
  },
  {
    "type": "company_domain_to_employees",
    "label": "List Employees by Company Domain",
    "category": "Companies",
    "credits": 1,
    "perEmployeeBilling": true,
    "alwaysAsync": true,
    "altType": null,
    "inputLabel": "Company Domain",
    "inputHelp": "The company's domain, not its name — tesla.com, not Tesla.",
    "example": "tesla.com",
    "outputField": null,
    "outputKind": "list",
    "params": [
      {
        "name": "department",
        "label": "Department",
        "type": "string"
      },
      {
        "name": "seniority",
        "label": "Seniority",
        "type": "string"
      },
      {
        "name": "employee_count",
        "label": "Max Employees",
        "type": "integer"
      }
    ]
  },
  {
    "type": "company_name_to_employees",
    "label": "List Employees by Company Name",
    "category": "Companies",
    "credits": 1,
    "perEmployeeBilling": true,
    "alwaysAsync": true,
    "altType": null,
    "inputLabel": "Company Name",
    "inputHelp": "The company's name.",
    "example": "Tesla",
    "outputField": null,
    "outputKind": "list",
    "params": [
      {
        "name": "department",
        "label": "Department",
        "type": "string"
      },
      {
        "name": "seniority",
        "label": "Seniority",
        "type": "string"
      },
      {
        "name": "employee_count",
        "label": "Max Employees",
        "type": "integer"
      }
    ]
  },
  {
    "type": "linkedin_company_to_employees",
    "label": "List Employees from LinkedIn Company",
    "category": "Companies",
    "credits": 1,
    "perEmployeeBilling": true,
    "alwaysAsync": true,
    "altType": null,
    "inputLabel": "LinkedIn Company Page URL",
    "inputHelp": "A LinkedIn company page URL.",
    "example": "https://www.linkedin.com/company/tesla-motors",
    "outputField": null,
    "outputKind": "list",
    "params": [
      {
        "name": "department",
        "label": "Department",
        "type": "string"
      },
      {
        "name": "seniority",
        "label": "Seniority",
        "type": "string"
      },
      {
        "name": "employee_count",
        "label": "Max Employees",
        "type": "integer"
      }
    ]
  },
  {
    "type": "linkedin_company_to_linkedin_info",
    "label": "Get LinkedIn Company Details",
    "category": "Companies",
    "credits": 6,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "LinkedIn Company Page URL",
    "inputHelp": "A LinkedIn company page URL.",
    "example": "https://www.linkedin.com/company/tesla-motors",
    "outputField": null,
    "outputKind": "object",
    "params": []
  },
  {
    "type": "linkedin_post_to_reactions",
    "label": "Get LinkedIn Post Reactions",
    "category": "Social",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "LinkedIn Post URL",
    "inputHelp": "A LinkedIn post URL.",
    "example": "https://www.linkedin.com/posts/someone_activity-123",
    "outputField": null,
    "outputKind": "list",
    "params": []
  },
  {
    "type": "instagram_lookup",
    "label": "Look Up an Instagram Profile",
    "category": "Social",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": "instagram_profile_to_instagram_info",
    "inputLabel": "Instagram Handle or URL",
    "inputHelp": "An Instagram handle or profile URL.",
    "example": "@nasa",
    "outputField": null,
    "outputKind": "object",
    "params": []
  },
  {
    "type": "b2b_data_lookup",
    "label": "B2B Data Lookup (Any Input)",
    "category": "Discovery",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": false,
    "altType": null,
    "inputLabel": "Company or Person Identifier",
    "inputHelp": "Use this only when you do not know the input type. A specific operation is more reliable.",
    "example": "tesla.com",
    "outputField": null,
    "outputKind": "object",
    "params": []
  },
  {
    "type": "leads_finder_ai",
    "label": "Find Leads with AI",
    "category": "Discovery",
    "credits": 1,
    "perEmployeeBilling": false,
    "alwaysAsync": true,
    "altType": null,
    "inputLabel": "Describe the Leads You Want",
    "inputHelp": "Plain English — job titles, industry, company size, location.",
    "example": "VP Sales at B2B SaaS startups in the United States",
    "outputField": null,
    "outputKind": "list",
    "params": [
      {
        "name": "fetch_count",
        "label": "Number of Leads",
        "type": "integer"
      }
    ]
  }
];

/** Looks an operation up by its API type. */
function lfOperation(type) {
  for (var i = 0; i < LINKFINDER_OPERATIONS.length; i++) {
    if (LINKFINDER_OPERATIONS[i].type === type) return LINKFINDER_OPERATIONS[i];
  }
  return null;
}
