/**
 * Generates searches/ from integrations/catalog/operations.json.
 *
 * Every operation the API supports becomes exactly one Zapier search, with its real
 * credit cost in the description — a Zap builder picking "Find Phone from LinkedIn
 * Profile" should see that it costs 50 credits before they schedule it over a list.
 *
 * Run `npm run build` after the catalog changes. Do not hand-edit searches/.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(readFileSync(join(HERE, '..', 'catalog', 'operations.json'), 'utf8'));

const SEARCH_DIR = join(HERE, 'searches');
rmSync(SEARCH_DIR, { recursive: true, force: true });
mkdirSync(SEARCH_DIR, { recursive: true });

const credits = (n) => (n === 1 ? '1 credit' : `${n} credits`);

/** The thing this search returns, as a Zapier "noun" — shown as "Find a(n) <noun>". */
function nounFor(op) {
  if (op.output.kind === 'list') return 'Result';
  if (op.output.kind === 'object') return op.category === 'company' ? 'Company' : 'Profile';
  return {
    email: 'Email',
    phone: 'Phone',
    linkedin_url: 'LinkedIn URL',
    website: 'Website',
    employee_count: 'Employee Count',
  }[op.output.field] ?? 'Result';
}

function descriptionFor(op) {
  const cost = op.perEmployeeBilling
    ? 'Billed 0.5 credits per employee returned.'
    : `Costs ${credits(op.credits)} per lookup, including lookups that find nothing.`;
  return `${op.label} using LinkFinder AI. ${cost}`;
}

function inputFieldsFor(op) {
  const fields = [
    {
      key: 'input_data',
      label: op.input.label,
      type: 'string',
      required: true,
      helpText: op.input.help,
      placeholder: String(op.input.example),
    },
  ];

  for (const param of op.params) {
    const field = {
      key: param.name,
      label: param.label,
      type: param.type === 'integer' ? 'integer' : 'string',
      required: false,
      helpText: param.help,
    };
    if (param.default !== undefined) field.default = String(param.default);
    fields.push(field);
  }

  return fields;
}

/** Zapier builds its field picker from the sample, so it has to be shaped like a real result. */
function sampleFor(op) {
  if (op.output.kind === 'scalar') {
    return { id: String(op.output.sample), value: op.output.sample, [op.output.field]: op.output.sample };
  }
  const sample = op.output.sample;
  const identifier = sample.linkedinUrl ?? sample.linkedin_url ?? sample.website ?? sample.email ?? sample.username ?? sample.name;
  return { id: String(identifier ?? '1'), ...sample };
}

/** Turns snake_case / camelCase sample keys into the labels shown in the Zap editor. */
function labelise(key) {
  return key
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .replace(/\bUrl\b/, 'URL')
    .replace(/\bLinkedin\b/, 'LinkedIn');
}

function outputFieldsFor(op, sample) {
  return Object.entries(sample)
    .filter(([key]) => key !== 'id')
    .map(([key, value]) => {
      const field = { key, label: labelise(key) };
      if (typeof value === 'number') field.type = 'integer';
      if (typeof value === 'boolean') field.type = 'boolean';
      return field;
    });
}

const files = [];

for (const op of catalog.operations) {
  const sample = sampleFor(op);

  // Only what lib/linkfinder.js actually reads at run time — keeping this small
  // means a catalog change cannot leave stale copy embedded in a search file.
  const operationMeta = {
    type: op.type,
    inputLabel: op.input.label,
    params: op.params.map((p) => p.name),
    outputField: op.output.field ?? null,
    altType: op.altType,
  };

  const asyncNote = op.alwaysAsync
    ? '\n// Always asynchronous: the API returns a job and the search polls it until it\n// resolves or Zapier runs out of time waiting.'
    : '';

  const source = `'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.
//
// ${op.label} — ${op.perEmployeeBilling ? '0.5 credits per employee returned' : credits(op.credits)}.${asyncNote}

const { runEnrichment } = require('../lib/linkfinder');

const OPERATION = ${JSON.stringify(operationMeta, null, 2).replace(/\n/g, '\n')};

module.exports = {
  key: '${op.key}',
  noun: ${JSON.stringify(nounFor(op))},

  display: {
    label: ${JSON.stringify(op.label)},
    description: ${JSON.stringify(descriptionFor(op))},
  },

  operation: {
    inputFields: ${JSON.stringify(inputFieldsFor(op), null, 6).replace(/\n {6}}/g, '\n    }').replace(/\n {4}]/g, '\n    ]')},

    perform: (z, bundle) => runEnrichment(z, bundle, OPERATION),

    sample: ${JSON.stringify(sample, null, 6).replace(/\n {4}}/g, '\n    }')},

    outputFields: ${JSON.stringify(outputFieldsFor(op, sample), null, 6).replace(/\n {4}]/g, '\n    ]')},
  },
};
`;

  writeFileSync(join(SEARCH_DIR, `${op.key}.js`), source);
  files.push(op);
}

const index = `'use strict';

// GENERATED by build.mjs from integrations/catalog/operations.json. Do not edit.

${files.map((op) => `const ${op.key} = require('./${op.key}');`).join('\n')}

module.exports = {
${files.map((op) => `  [${op.key}.key]: ${op.key},`).join('\n')}
};
`;

writeFileSync(join(SEARCH_DIR, 'index.js'), index);

console.log(`zapier: generated ${files.length} searches from spec v${catalog.specVersion}`);
